let data = [
  {
    name: "1",
    age: "42",
    gender: "FEMALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "2",
    age: "42",
    gender: "MALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "3",
    age: "23",
    gender: "MALE",
    booth_type: "STORNG",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "4",
    age: "42",
    gender: "FEMALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "5",
    age: "42",
    gender: "MALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "6",
    age: "23",
    gender: "MALE",
    booth_type: "STORNG",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "7",
    age: "42",
    gender: "FEMALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "8",
    age: "42",
    gender: "MALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "9",
    age: "23",
    gender: "MALE",
    booth_type: "STORNG",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "10",
    age: "42",
    gender: "FEMALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "11",
    age: "23",
    gender: "MALE",
    booth_type: "STORNG",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
  {
    name: "12",
    age: "42",
    gender: "FEMALE",
    booth_type: "WEAK",
    religion: "HINDU",
    employment: "EMPLOYED",
  },
];
